apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: prod
  labels:
    app: myapp
    type: frontend
spec:
  replicas: 3
  template:
    metadata:
      name: myreplicaset
      labels:
        app: myapp
    spec:
      containers:
      - name: mywebserver
        FROM: redis
        COPY: redis.conf /usr/local/etc/redis/redis.conf
        CMD: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  selector:
    matchLabels:
      app: myapp