apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: frontend
  labels:
    app: myapp
    type: frontend
spec:
  replicas: 3
  template:
    metadata:
      name: myreplicaset
      labels:
        app: myapp
    spec:
      containers:
       - name: httpds
         image: httpd:2.4
         COPY: ./public-html/ /usr/local/apache2/htdocs/
         command: [ "-dit --name my-apache-app -p 8080:80 -v "$PWD":/usr/local/apache2/htdocs/ httpd:2.4" ]
              
         volumeMounts:
             - name: efs-pv
               mountPath: "/var/www/html"
      volumes:
        - name: efs-pv
          persistentVolumeClaim:
          claimName: efs-claim

  selector:
    matchLabels:
      app: myapp
